[tool.poetry]
name = "gerador-de-questoes-didaxis"
version = "4.3.1"
description = "O Gerador de Questões Didaxis é um programa que permite criar e gerenciar questões didáticas. Com o novo layout e recursos aprimorados, foram feitas alterações significativas para melhorar a experiência do usuário."
authors = ["Edimar de Sá <edimarfreitas95@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
icecream = "^2.1.3"
pandas = "^2.1.1"
customtkinter = "^5.2.1"
openpyxl = "^3.1.2"
Pillow = "^10.1.0"
requests = "^2.31.0"
pyspellchecker = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
