from Modules.janelas.janelaquantidadedequestoes import JanelaQuantidadeDeQuestoes
from Modules.janelas.janelaparametrosdaquestao import JanelaParametrosDaQuestao
from Modules.janelas.janelaenunciadodaquestao import JanelaEnunciadoDaQuestao
from Modules.janelas.janelaopcoesdaquestao import JanelaOpcoesDaQuestao
from Modules.janelas.janeladebotoes import JanelaDeBotoes
