from .janelaquantidadedequestoes import JanelaQuantidadeDeQuestoes
from .janelaparametrosdaquestao import JanelaParametrosDaQuestao
from .janelaenunciadodaquestao import JanelaEnunciadoDaQuestao
from .janelaopcoesdaquestao import JanelaOpcoesDaQuestao
from .janeladebotoes import JanelaDeBotoes
from .janeladequestoes import JanelaDeQuestoes
from .janeladeconfiguracoes import JanelaDeConfiguracoes
