site_name: Editor de questões
repo_url: https://github.com/EdimarDeSa/gerador_de_questoes_didaxis
repo_name: Edimar de Sá/Editor de questões Didaxis
edit_uri: tree/main/docs


theme:
  name: material
  language: pt-BR
  logo: assets/prova_colorido 16x16.png
  favicon: assets/prova_colorido 16x16.png